### 프로그램 오류의 종류

1. 컴파일에러 (compile-time error): 컴파일 시점에 발생하는 에러

2. 런타임 에러 (runtime error): 실행 시에 발생하는 에러

3. 논리적 에러 (logical error): 의도한 것과 다르게 동작하는 에러

### 자바에서 runtime 오류의 구분

1. 에러 (error) : `OutOfMemoryError` 나 `StackOverflowError`와 같이 무거운 오류

2. 예외 (exception) : 발생하더라도 수습될 수있는 비교적 덜 무거운 오류

### 예외 클래스의 계층 구조

- 모든 객체는 `Object`의 상속을 받기 때문에 최상위 클래스이고
- 일반적으로 예외 클래스의 최상위 클래스는 `Exception` 클래스이다.

구글링 추천

### Exception 클래스의 그룹

1. Exception 클래스: 클라이언트의 실수와 같은 외적인 요인에의해 발생
   - HTTP State Code로 대응해줘야한다.
   - ex) `ClassNotFoundException`, `IOException`

`checked 예외`: `컴파일 단계`에서 예측가능한 확실한 예외에 대해서는 잡아줄 수 있다.

2. RuntimeException 클래스: 프로그래머의 실수에 의해 발생

- ex) `NullPointerException`, `IndexOutOfBoundsException`

`unchecked 예외`: 오직 `runtime 단계`에서만 예외를 발생시킨다.

### 발생한 예외를 처리하지못하면

1. 프로그램이 비정상 종료되며
2. `JVM`의 `예외처리기(UncaughtExceptionHandler)`에 의해 화면에 출력된다.

### try-catch 문에서의 `catch`

기본적으로 `try-catch`문은 아래와 같은 형식을 띄는데

```
try{
    블럭
} catch (매개변수타입 매개변수){
    블럭
}
```

- Exception 또한 Object의 상속받은 객체이다.
- try 블럭에서 `예외`가 발생했을때 catch로 넘어가게되는데

1. 발생한 `예외`가 매개변수타입의 `instance`인지 확인한다.
2. 없다면 다음 `catch`문으로 넘어간다.
3. 있다면 해당 `매개변수타입`과 매개변수이름의 식별자로 `예외 인스턴스`가 생성된다.
4. 당연히 catch 블럭안의 로직도 실행된다.

### `printStackTrace()`와 `getMessage()`

- `getMessage()`: 생성된 예외 인스턴스 `Message` 멤버변수의 `getter()`
- `printStackTrace()`: 예외발생 당시 `콜스택`에 있던 메서드 정보와 메세지 출력

### JDK 1.7에 추가된 멀티 cathch 블럭

```
catch(ExceptionA | ExceptionB e){
    ...
}
```

- 각 `Exception`들 간에 상속관계가 없어야한다. (Exception 클래스 사용불가능)

### 메서드에 예외 선언

```
void method() throws Exception1, Exception2, ... {
    ...
}
```

- `Exception1`에 대한 자손클래스에 대한 예외까지 던져지게 된다.
- Exception에 대해 관련한 코드를 작성할때는 상속관계 또한 고려해줘야한다.

### 빌트인 메서드의 API를 살펴보면 처리해야할 Exception의 정보를 얻을 수 있다.

https://docs.oracle.com/javase/7/docs/api/java/lang/Object.html#wait()

`public final void wait() throws InterruptedException`

- `java.lang.Obejct`클래스의 `wait()`메서드

### 호출 스택 (call stack)의 정보

콜 스택에는 아래와 같은 정보가 출력된다.

- 예외가 발생하기 까지의 호출된 `메서드` 들
- `제일 위`에는 예외가 발생한 메서드
- 어떤 메서드가 어떤 다른 메서드를 호출했는지

### 예외를 직접 처리할지 vs 예외를 한곳에서 처리할지

1. `try-catch-finally` 등을 이용한 예외를 직접 코드에서 처리하는 것
2. 예측가능한 예외에 대해서 한곳에서 처리하는 것

첫 번째 예시의 경우는 해당 코드가 작동하지 않으면 다음 단계로 넘어갈수 없을때 사용한다.
두 번째의 예시의 경우 서비스가 해당 예외에 대해 관리하지 않도록 정의한 예외에 대해 사용한다.

즉,

- `1번`의 경우: `RuntimeException` 클래스
- `2번`의 경우: `RuntimeException` 클래스를 제외한 `Exception` 클래스의 경우

### try-with-resource

JDK1.7등장
임시적으로 필요한 `객체`를 사용할때 유용

- try문이 끝날때 자동으로 `.close()`메서드가 호출되므로 `AutoCloseable` 인터페이스로 구현된 것만 사용할 수 있다.

- `AutoCloseable 인터페이스 :`
  https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html

### 사용자 정의 예외

```
class MyException extends Exception { // RuntimeException 둘 중 하나사용
    private final int ERR_CODE;

    MyExeption(String msg, int errCode) {
        super(msg);
        ERR_CODE = errCode;
    }

    MyException (String msg) {
        this(msg, 100);
    }

    public int getErrCode() {
        return ERR_CODE;
    }

    //getMessage()는 Exeption의 상속을 받음

}
```

### checked예외를 unchecked예외로 바꾸기

`checked`예외는 프로그램을 종료시키므로 위험하다. (동기자체는 경험이 적은 사람도 제대로된 자바코드를 만들게 함에 있음)
이것을 `unchecked`예외로 바꾸기 위해서 `chained exception`의 개념이 필요하다.

```
static void startInstall() throws SpaceException {
    if(!enoughSpace()) {
        throw new SpaceException("설치 공간 부족"); // checked 예외
    }

    if(!enoughMemory()) {
        throw new RuntimeException(new MemoryException("메모리 공간 부족")); // 이 부분
    }
}
```

### `initCause`

https://docs.oracle.com/javase/7/docs/api/java/lang/Throwable.html#initCause(java.lang.Throwable)

- 예외에는 큰 범위의 예외와 그에 대한 상세한 예외가 존재할 수 있다.
- 해당 큰예외에 대해 `.initCause()` 메서드를 이용한 원인 예외를 담을 수 있다.

1. `checked 예외`

```
InstallException: 설치 중 예외발생
	at ChainedExceptionEx.install(ChainedExceptionEx.java:24)
	at ChainedExceptionEx.main(ChainedExceptionEx.java:4)
Caused by: MemoryException: 메모리가 부족합니다.
	at ChainedExceptionEx.startInstall(ChainedExceptionEx.java:38)
	at ChainedExceptionEx.install(ChainedExceptionEx.java:17)
	... 1 more
```

2. `uncheked 예외`

```
InstallException: 설치 중 예외발생
	at ChainedExceptionEx.install(ChainedExceptionEx.java:30)
	at ChainedExceptionEx.main(ChainedExceptionEx.java:4)
Caused by: java.lang.RuntimeException: MemoryException: 메모리가 부족합니다.
	at ChainedExceptionEx.startInstall(ChainedExceptionEx.java:45)
	at ChainedExceptionEx.install(ChainedExceptionEx.java:19)
	... 1 more
Caused by: MemoryException: 메모리가 부족합니다.
	... 3 more
```

- `checked`예외를 `unchecked`로 한번 바꿔주었기 때문에 `RuntimeException`안에 또다른 `Caused by` 있는 것을 볼 수 있다.
